files:
  - '**/*.md'  
  - '!ecosystem/clients/index.md'
  - '!ecosystem/libraries/index.md'
  - '!ecosystem/modules/index.md'
  - '!ecosystem/tools/index.md'
  - '!docs/reference/modules/modules-api-ref.md'
dictionaries:
  - wordlist
no-suggestions: true
quiet: true
