name: Trigger master website deploy
on:
  push:
    branches:
      - master

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "'$DATA'" | xargs \
          curl \
          -X POST https://api.netlify.com/build_hooks/${NETLIFY_BUILD_HOOK_ID} \
          -d
        env:
          NETLIFY_BUILD_HOOK_ID: ${{ secrets.NETLIFY_BUILD_HOOK_ID }}
          DATA: '{"type": "core", "id": "redis_docs", "repository":"${{ github.repository }}", "sha":"${{ github.sha }}", "ref":"${{ github.ref }}"}}'
